spring.application.name=ProductInventoryManagementSystem

spring.datasource.url=jdbc:mysql://localhost:3306/products?useSSL=false
spring.datasource.username=root
spring.datasource.password=Ragu9659@
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql: true 

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

